#! /usr/bin/env bash

NOCOLOR='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

SERVER="localhost:8082"

SUPPORTED_COMMANDS=(
    'help'
    'tests'
    'browser-sync'
    'status'
)

function ctrl_c() {
    if [ $# -gt 0 ];
    then
        pkill browser-sync
    fi
}

if [ $# -gt 0 ]
then
    supported_command=false
    for command in ${SUPPORTED_COMMANDS[@]};
    do
        if [ "${command}" == "$1" ];
        then
            supported_command=true
            break
        fi
    done
    if [ "${supported_command}" = false ];
    then
        echo -e "Unknown parameter ${ORANGE}${BOLD}${1}${NORMAL}${NOCOLOR}. Type ${GREEN}${BOLD}run -help${NORMAL} to know what the valid parameters are."
        exit 1
    fi
fi

if [ $# -gt 0 ] && [ $1 = 'help' ]
then
    echo -e "${ORANGE}${BOLD}Usage:${NORMAL}${NOCOLOR}"
    echo -e " ${BOLD}run${NORMAL}               Starts the PHP web server and listen to localhost:8082"
    echo -e " ${BOLD}run tests${NORMAL}         Runs application test suite"
    echo -e " ${BOLD}run browser-sync${NORMAL}  Run with browser-sync"
    echo -e " ${BOLD}run status${NORMAL}        Check if the current commit is on production"
    echo ""
    echo "Additional parameters will be ignored."
    exit 1
fi

if [ $# -gt 0 ] && [ $1 = 'tests' ]
then
    composer test:all
    exit 1
fi

if [ $# -gt 0 ] && [ $1 = 'status' ]
then
    local=`git rev-parse master`
    prod=`curl -s https://whattrainisitnow.com/deployed-version.txt`
    echo -e "$GREEN""Checking if the latest commit is what we have in production""$NORMAL"
    echo "Local : $local"
    echo -n "Prod  : $prod"
    if [ $local == $prod ]
    then
        echo ""
        echo -en "$GREEN""Yes, we are good""$NORMAL"
    elif [[ condition ]]; then
        x=$(($(git rev-list --count $prod..$local)))
        echo ""
        echo -en "$ORANGE""No, production is $x commit(s) behind""$NORMAL"
    fi
    exit 1
fi

echo -e "${GREEN}${BOLD}Launching PHP development server on http://${SERVER}${NORMAL}${NOCOLOR}"

if command -v browser-sync &> /dev/null; then
    if [ $# -gt 0 ] && [ $1 = 'browser-sync' ]
    then
        echo -e "${GREEN}browser-sync is installed on the system, launching it in the background${NOCOLOR}"
        browser-sync start --proxy "localhost:8082" --files "**/*" &
    else
        echo -e "${ORANGE}browser-sync is installed on the system but won't be launched${NOCOLOR}"
    fi
fi

php -S ${SERVER} -t public/ app/inc/router.php

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT