#! /usr/bin/env bash

NOCOLOR='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[38;5;208m'  # 256-colour palette orange, ANSI 33 is yellow
GRAY='\e[2;37m'
BLACK="\033[0;30m"        # Black
RED="\033[0;31m"          # Red
YELLOW="\033[0;33m"       # Yellow
BLUE="\033[0;34m"         # Blue
PURPLE="\033[0;35m"       # Purple
CYAN="\033[0;36m"         # Cyan
WHITE="\033[0;37m"        # White
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

SERVER="localhost:8082"

SUPPORTED_COMMANDS=(
    'help'
    'tests'
    'browser-sync'
    'status'
)

# Define it for the whole script session
# This disables twig caching and activate debugging tools
export DEV_MODE=true

# Stop browser-sync when the script exits (Ctrl-C on the PHP server included)
BROWSER_SYNC_PID=''
function cleanup() {
    if [ -n "${BROWSER_SYNC_PID}" ];
    then
        kill "${BROWSER_SYNC_PID}" 2> /dev/null
    fi
}
trap cleanup EXIT

if [ $# -gt 0 ]
then
    supported_command=false
    for command in ${SUPPORTED_COMMANDS[@]};
    do
        if [ "${command}" == "$1" ];
        then
            supported_command=true
            break
        fi
    done
    if [ "${supported_command}" = false ];
    then
        echo -e "Unknown parameter ${ORANGE}${BOLD}${1}${NORMAL}${NOCOLOR}. Type ${GREEN}${BOLD}./run help${NORMAL} to know what the valid parameters are."
        exit 1
    fi
fi

if [ $# -gt 0 ] && [ $1 = 'help' ]
then
    echo -e "${ORANGE}${BOLD}Usage:${NORMAL}${NOCOLOR}"
    echo -e " ${BOLD}run${NORMAL}               Starts the PHP web server and listen to localhost:8082"
    echo -e " ${BOLD}run tests${NORMAL}         Runs application test suite"
    echo -e " ${BOLD}run browser-sync${NORMAL}  Run with browser-sync"
    echo -e " ${BOLD}run status${NORMAL}        Check if the current commit is on production"
    echo ""
    echo "Additional parameters will be ignored."
    exit 0
fi

if [ $# -gt 0 ] && [ $1 = 'tests' ]
then
    composer test:all
    exit $?
fi

if [ $# -gt 0 ] && [ $1 = 'status' ]
then
    local=`git rev-parse master`
    dev=`curl -s https://dev.whattrainisitnow.nonprod.webservices.mozgcp.net/deployed-version.txt`
    prod=`curl -s https://whattrainisitnow.com/deployed-version.txt`
    echo -e "$GREEN""Checking if the latest commit is what we have in production""$NORMAL"
    echo -e "$GRAY""Dev   $dev""$NORMAL"
    echo "Local $local"
    echo -n "Prod  $prod"
    if [ $local == $prod ]
    then
        echo ""
        echo -en "$GREEN""Yes, we are good""$NORMAL"
    else
        x=$(($(git rev-list --count $prod..$local)))
        echo ""
        if [ $x == 1 ]
        then
            echo -en "$ORANGE""No, production is 1 commit behind""$NORMAL"
        else
            echo -en "$ORANGE""No, production is $x commits behind""$NORMAL"
        fi
    fi
    exit 0
fi

echo -e "${GREEN}${BOLD}Launching PHP development server on http://${SERVER}${NORMAL}${NOCOLOR}"

if command -v browser-sync &> /dev/null; then
    if [ $# -gt 0 ] && [ $1 = 'browser-sync' ]
    then
        echo -e "${GREEN}browser-sync is installed on the system, launching it in the background${NOCOLOR}"
        browser-sync start --proxy "localhost:8082" --files "**/*" &
        BROWSER_SYNC_PID=$!
    else
        echo -e "${ORANGE}browser-sync is installed on the system but won't be launched${NOCOLOR}"
    fi
fi

php -d opcache.jit=disable -S ${SERVER} -t public/ app/inc/router.php
